import Head from "next/head";
import Image from "next/image";
import HeroIllust from "public/images/illustration-hero.svg";
import MusicIco from "public/images/icon-music.svg";
import patternMov from "public/images/pattern-background-mobile.svg";
import patternDesk from "public/images/pattern-background-desktop.svg";
import { useBreakpoint } from "../hooks/useBreakpoint";

export default function Home() {
  const breakpoint = useBreakpoint();
  const pattImage = breakpoint.xl === true ? patternDesk : patternMov;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className="bg-[#E0E8FF] font-medium text-[#7280A7] h-full w-full p-5 flex justify-center items-center relative">
        <Image
          src={pattImage}
          alt="backPattern"
          className=" absolute z-0 top-0 w-full"
        ></Image>
        <div className="bg-white  z-10 flex flex-col items-center gap-8 rounded-2xl  ">
          <Image
            src={HeroIllust}
            alt="hero illust"
            className="rounded-t-2xl w-full"
          ></Image>
          <div className="flex flex-col items-center gap-6 px-6 mb-6">
            <h1 className="text-[#1F2F56] text-2xl font-black">
              Order Summary
            </h1>
            <p className="text-center px-2">
              You can now listen to millions of songs, audiobooks, and podcasts
              on any device anywhere you like!
            </p>
            <div className="flex items-center w-full p-4 justify-between bg-[#F5F7FF] rounded-xl">
              <div className="flex">
                <Image src={MusicIco} alt="music ico" className="mr-4"></Image>
                <div>
                  <p className="font-bold text-[#1F2F56] ">Annual Plan</p>
                  <p>$59.99/year</p>
                </div>
              </div>

              <p className="text-[#3829E0] underline hover:no-underline font-bold hover:text-[#3829E0]/60 hover:cursor-pointer">
                Change
              </p>
            </div>
            <button className="bg-[#3829E0] w-full p-4 text-white font-bold rounded-xl hover:bg-[#3829E0]/60">
              Proceed to Payment
            </button>
            <button className="font-bold hover:text-[#1F2F56]">
              Cancel Order
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
